name: Python application

on:
  push:
    branches: [ "shubh" ]




jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
        token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Test with pytest
      run: |
        export PYTHONPATH=src
        pytest
        

    - name: create pull request
      id: open-pr
      uses: repo-sync/pull-request@v2
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        destination_branch: ${{ github.event.repository.default_branch }}
        pr_title: "[Automated] Merge ${{ github.ref_name }} into ${{ github.event.repository.default_branch }}"
        pr_body: "Automated Pull Request"
        pr_reviewer: "ssingh41"

 