# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ "shubham_branch" ]


permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
        token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      run: |
        export PYTHONPATH=src
        pytest
    - name: create pull request
      id: open-pr
      uses: repo-sync/pull-request@v2
      with:
        github_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        destination_branch: "main"
        pr_title: "[Automated] Merge ${{ github.ref_name }} into ${{ github.event.repository.default_branch }}"
        pr_body: "Automated Pull Request"

    # https://github.com/marketplace/actions/enable-pull-request-automerge
    - name: enable automerge
      if: steps.open-pr.outputs.pr_number != ''
      uses: peter-evans/enable-pull-request-automerge@v2
      with:
        token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        pull-request-number: ${{ steps.open-pr.outputs.pr_number }}
        merge-method: merge

